- name: ensure tex tools are installed
  yum: pkg={{ item }}
  with_items:
    - texlive
    - texlive-latex
    - texlive-xdvi
    - texlive-adjustbox
    - texlive-apacite
    - texlive-babel
    - texlive-babel-english
    - texlive-babelbib
    - texlive-biblatex
    - texlive-biblatex-apa
    - texlive-cite
    - texlive-csquotes
    - texlive-fancyhdr
    - texlive-floatrow
    - texlive-koma-script
    - texlive-lastpage
    - texlive-tools
    - texlive-german
    - texlive-babel-german
    - texlive-hyphen-german
    - latex-mk
    - vim-latex
  tags:
    - tex
