- name: ensure ssmtp software is installed
  yum: name=ssmtp

- name: ensure ssmtp configuration is installed
  template: src=ssmtp.conf.j2
            dest=/etc/ssmtp/ssmtp.conf
            owner=root group=mail mode=0640
