- name: ensure gnome tools are installed
  dnf: name={{ item }}
  with_items:
    - "@base-x"
    - epiphany
    - gnome-backgrounds
    - gnome-contacts
    - gnome-calendar
    - gnome-documents
    - gnome-web-photo
    - gnome-photos
    - gnome-music
    - gnome-maps
    - gnome-weather
    - gnome-rdp
    - gnome-terminal
    - gnome-power-manager
    - gnome-activity-journal
    - gnome-tweak-tool
    - dconf-editor
    - gmpc
    - mpdris2
    - totem
    - vinagre
  tags:
    - fedora-gui

- name: ensure multimedia software is installed
  dnf: name={{ item }}
  with_items:
    - ImageMagick
    - avidemux-qt
    - devede
    - easytag
    - vlc
    - gimp
    - inkscape
  tags:
    - fedora-gui

- name: ensure misc software is installed
  dnf: name={{ item }}
  with_items:
    - dnf-langpacks
    - gitg
    - virt-manager
    - deja-dup
    - deja-dup-nautilus
    - owncloud-client
    - owncloud-client-nautilus
    - xca
    - java-1.8.0-openjdk
  tags:
    - fedora-gui

- name: ensure gnucash is installed
  dnf: name={{ item }}
  with_items:
    - gnucash
    - gnucash-docs
    - libdbi-dbd-mysql
  tags:
    - fedora-gui

- name: ensure office is installed
  dnf: name="@libreoffice"
  tags:
    - fedora-gui

- command: rpm -q man-pages-de
  register: langpacks_installed
  changed_when: false

- name: ensure de langpacks are installed
  command: dnf -y langinstall de_CH
  when: langpacks_installed|failed
  tags:
    - fedora-gui
