- name: ensure gnome tools are at the latest version
  yum: pkg={{ item }} state=latest
  with_items:
    - "@^workstation-product-environment"
    - epiphany
    - gnome-web-photo
    - gnome-photos
    - gnome-music
    - gnome-maps
    - gnome-weather
    - gnome-rdp
    - gnome-power-manager
    - gnome-activity-journal
    - gnome-tweak-tool
    - gmpc
  tags:
    - fedora-gui

- name: ensure multimedia software is at the latest version
  yum: pkg={{ item }} state=latest
  with_items:
    - ImageMagick
    - avidemux-qt
    - devede
    - easytag
  tags:
    - fedora-gui

- name: ensure misc software is at the latest version
  yum: pkg={{ item }} state=latest
  with_items:
    - yum-langpacks
    - gitg
    - virt-manager
    - deja-dup
    - mirall
    - gramps
  tags:
    - fedora-gui

- name: ensure gnucash is at the latest version
  yum: pkg={{ item }} state=latest
  with_items:
    - gnucash
    - gnucash-docs
    - libdbi-dbd-mysql
  tags:
    - fedora-gui

- name: ensure office is at the latest version
  yum: pkg="@libreoffice" state=latest
  tags:
    - fedora-gui

- name: ensure de langpacks are installed
  command: yum -y langinstall de_CH
  tags:
    - fedora-gui

- name: ensure yum repository for google chrome is installed
  copy: src=google-chrome.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644
  tags:
    - fedora-gui
    - google-chrome

- name: ensure google chrome is at the latest version
  yum: name=google-chrome-stable state=latest
  tags:
    - fedora-gui
    - google-chrome

- file: src=/lib/systemd/system/graphical.target dest=/etc/systemd/system/default.target state=link
  tags:
    - fedora-gui
