- name: ensure gnome tools are installed
  package:
    name: "{{ item }}"
  with_items:
    - "@base-x"
    - epiphany
    - gnome-backgrounds
    - gnome-contacts
    - gnome-calendar
    - gnome-documents
    - gnome-web-photo
    - gnome-photos
    - gnome-music
    - gnome-maps
    - gnome-weather
    - gnome-rdp
    - gnome-terminal
    - gnome-power-manager
    - gnome-activity-journal
    - gnome-tweak-tool
    - dconf-editor
    - gmpc
    - totem
    - vinagre

- name: ensure multimedia software is installed
  package:
    name: "{{ item }}"
  with_items:
    - ImageMagick
    - avidemux-qt
    - devede
    - easytag
    - vlc
    - gimp
    - inkscape

- name: ensure misc software is installed
  package:
    name: "{{ item }}"
  with_items:
    - gitg
    - virt-manager
    - deja-dup
    - deja-dup-nautilus
    - owncloud-client
    - owncloud-client-nautilus
    - xca
    - scudcloud
    - atom
    - nodejs
    - npm

- name: ensure gnucash is installed
  package:
    name: "{{ item }}"
  with_items:
    - gnucash
    - gnucash-docs
    - libdbi-dbd-mysql

- name: ensure office is installed
  package:
    name: "@libreoffice"
