- name: ensure mariadb test database is removed
  mysql_db: name=test state=absent

- name: ensure mariadb test user is removed
  mysql_user: name=test state=absent

- name: ensure mariadb root and anonymous users are removed
  mysql_user: name={{ item.name }} host={{ item.host }} state=absent
  with_items:
    - { name: root, host: "::1" }
    - { name: root, host: "localhost.localdomain" }
    - { name: root, host: "127.0.0.1" }
    - { name: root, host: "{{ ansible_fqdn }}" }
    - { name: root, host: "{{ ansible_nodename }}" }
    - { name: ~, host: "localhost.localdomain" }
    - { name: ~, host: "localhost" }
    - { name: ~, host: "{{ ansible_fqdn }}" }
    - { name: ~, host: "{{ ansible_nodename }}" }
