---
- name: ensure backup directories exist
  file:
    dest: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  with_items:
    - "/var/lib/backup/{{ ansible_hostname }}/etc"
    - "/var/lib/backup/{{ ansible_hostname }}/mpd"
    - "/var/lib/backup/{{ ansible_hostname }}/db"

- name: ensure backup cron scripts are installed
  template:
    src: "backup-{{ item }}.sh.j2"
    dest: "/etc/cron.daily/{{ item }}_backup.sh"
    owner: root
    group: root
    mode: 0750
  with_items:
    - mpd
    - mariadb
    - owncloud
