- name: ensure dnf-automatic is installed
  package:
    name: dnf-automatic

- name: ensure dnf-automatic timer is active
  service:
    name: dnf-automatic.timer
    enabled: yes
    state: started

- name: ensure dnf-automatic is configured to emit via email
  lineinfile:
    dest: /etc/dnf/automatic.conf
    regexp: "emit_via ="
    line: "emit_via = email"
