eclipse_owner: "{{ lookup('env','USER') }}"
eclipse_group: "{{ eclipse_owner }}"
eclipse_base_dir: "/opt/eclipse"

eclipse_flavor: "java"
eclipse_name: "luna"
eclipse_release: "SR1"

eclipse_version: "{{eclipse_flavor}}-{{eclipse_name}}-{{eclipse_release}}"
eclipse_archive: "eclipse-{{eclipse_version}}-linux-gtk-x86_64.tar.gz"
eclipse_url: "https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/{{eclipse_name}}/{{eclipse_release}}/{{eclipse_archive}}&r=1"

eclipse_home_dir: "{{eclipse_base_dir}}/{{eclipse_flavor}}-{{eclipse_name}}-{{eclipse_release}}"
